### ISSUE TITLE
Cannot find module './api_key' 

### ISSUE THREAD

**Issue by gatarelib** [notnavindu/whatismybrowser-API-with-nodejs-sample#1]
`$ node app.js`

`module.js:550
    throw err;
    ^
`
`Error: Cannot find module './api_key'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Libère\Desktop\assets\whatismybrowser-API-wi
th-nodejs-sample\app.js:6:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
`

**Comment by notnavindu** [comment]
You have to make a file named 'api_key.js' and put your key inside that file. Please read https://github.com/notnavpy/whatismybrowser-API-with-nodejs-sample/blob/2d50f6c688dce7c594c9b6bf17b6121627e54fac/api_key.md

**Comment by gatarelib** [comment]
Awesome, Thank you.

> You have to make a file named 'api_key.js' and put your key inside that file. Please read https://github.com/notnavpy/whatismybrowser-API-with-nodejs-sample/blob/2d50f6c688dce7c594c9b6bf17b6121627e54fac/api_key.md
